language: objective-c
osx_image: xcode10.2
script: set -o pipefail && xcodebuild -project msgpack-objc.xcodeproj -scheme Tests -destination platform\=iOS\ Simulator,OS\=11.4,name\=iPhone\ 8 test | xcpretty
